### Introduction

1. What is feature extraction from text or text representation or text vectorization?

Converting the text into number format

2. Why do we need it?

We need to create the feature.

eg: Garbeg in Garbeg out, so we needto get the insight from the data and create good feature.

3. Why it is difficult ?

Converting image to number is easy(Image formed with pixel size 255 which is number), speech recognization is also easy.
Textual data it is difficult since people do spelling mistake and short forms etc...

4. What is the core idea and the techniques.

We have to get the simentic meaning of the text meaning.

Techniques: 
1. 1 hot encoding.
2. Bag of words.
3. ngrams.
4. tfidf.
5. custom features.
6. Embedding ( word2vec)



### Common Terms

1. Corpus (C) : Combinarion of all the words in the entire data set which contains repeated word as well.

2. Vocabulary (V) : count of unique number of words which is used in the corpus.

3. Document (D) : Each individual review is called as document. 

4. Word (W) : Each document individual word.

#### 1 Hot Encoding
 Converting the each word into v dimentional vector.

#### This techniques is not used in the present world.

Pros:
1. Very Intevitive.
2. Easy to train the examples.

Cons:
1. Sparcity is the major problem which makes training overfitting.
2. Required more and more data to avoid (OOV) out of vocabolary.
3. No fixed size.
4. No capturing of simantic meaning this is the major disadvantage of the one hot encoding.


### Bag of words.

#### Most used in text classifications.

1. Creating the vocabolary with the text present in the corpus.
2. Creating the document with the vocabolary.
3. In the bag of words order of the words doesn't matter .
4. We convert into vectorization then find the cosine distance between the vectors to find the predictions.

#### Advantage:
1. Simple and intevitive.
2. handles the OOV(Out of Vocabolary) and fixed size will be maintained.
3. We can capture better simantic meaning compare to One hot encoding

#### Disadvantage:
1. Sparcity and over fitting.
2. OOV is present since we are ignoring if we find any oov.
3. We are ignoring the ordering (This is the major disadvantage), if we change the order the meaning of the sentance will change.

In [2]:
import pandas as pd
import numpy as np

In [6]:
### Implimentation of bag of words

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

#####  Hyper parameter tuning
1. lower_case =True (will convert the words into lower case)
2. stop_words = we can remove stop_words from the language
3. binary = True(Most used in Sentiment Analysis).
4. max_features = To remove the rare words we use this and it's like experiment since it's a hyper parameter tuning.


In [1]:
data = {'columns':['Hi My Name is Manoj','I work as a Generalized Data Scientist']}

In [3]:
df = pd.DataFrame(data)

In [4]:
df.head()

columns
0                     Hi My Name is Manoj
1  I work as a Generalized Data Scientist

In [7]:
#Bag of words

bow = cv.fit_transform(df['columns'])


In [11]:
print(bow[0].toarray())
print(bow[1].toarray())
#We just found the 2 vectorized array

[[0 0 0 1 1 1 1 1 0 0]]
[[1 1 1 0 0 0 0 0 1 1]]


In [13]:
print(cv.vocabulary_)

{'hi': 3, 'my': 6, 'name': 7, 'is': 4, 'manoj': 5, 'work': 9, 'as': 0, 'generalized': 2, 'data': 1, 'scientist': 8}


### Bag of N-Grams

This is quit similary to bag of words.

Advantage:
We combine multiple words to form the vocabolary.


combination of 2 words is bi-gram.
combination of 3 words is tri-gram.
etc...
eg: For Bi-gram => ['Hi my','my name','name is','is manoj']
eg: for tri-gram => ['Hi my name','name is manoj']


Benefit:
1. Able to capture semantic meaning of the sentence using n-gram
2. Easy to impliment.

Disadvantage:
1. The dimention of the vocabulary will be increased since number of features will be increased
2. Out of Vocabulary is still the issue since it will not consider the OOV as in bag of words.

In [23]:
#Implimentation of n-grams

### Implimentation of bag of words

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(1,2)) # unigram and Bigram
#cv = CountVectorizer(ngram_range=(2,2)) # Only Bigram
#cv = CountVectorizer(ngram_range=(3,3)) # Only trigram
#cv = CountVectorizer(ngram_range=(1,3)) #uni, bi and trigram

In [24]:
bi_gram = cv.fit_transform(df['columns'])

In [25]:
cv.vocabulary_
#We saw bigram.

{'hi': 6,
 'my': 11,
 'name': 13,
 'is': 8,
 'manoj': 10,
 'hi my': 7,
 'my name': 12,
 'name is': 14,
 'is manoj': 9,
 'work': 16,
 'as': 0,
 'generalized': 4,
 'data': 2,
 'scientist': 15,
 'work as': 17,
 'as generalized': 1,
 'generalized data': 5,
 'data scientist': 3}

### TFIDF : TERM FREQUENCY INVERSE DOCUMENT FREQUENCY.

TF-IDF stands for term frequency-inverse document frequency and it is a measure, used in the fields of information retrieval (IR) and machine learning, that can quantify the importance or relevance of string representations (words, phrases, lemmas, etc) in a document amongst a collection of documents.

    (NUMBER OF OCCURANCE OF TERM T IN DOCUMENT D)
TF =--------------------------------------------
    (TOTAL NUMBER OF TERMS IN THE DOCUMENT D)
    
                      (TOTAL NUMBER OF DUCUMENTS IN THE CORPUS)
IDF = LOG to base n ------------------------------------------
                       (NUMBER OF DOCUMENTS WITH TERM T IN THEM)
   
   Why log is used in TDF:  We minimise the large number into a smaller number normalization with the help of log
   eg: without log we have 100000000, with log we get 1000, simple.
   
 total tfidf = tf * idf


Advantage:
1. Main useful for the information reterival eg: search reterval

Disadvantage:
1. Sparcity is more.
2. OOV.
3. Dimentionality will be increased so it needs more computational power and makes over fitting.


In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['columns']).toarray()

array([[0.       , 0.       , 0.       , 0.4472136, 0.4472136, 0.4472136,
        0.4472136, 0.4472136, 0.       , 0.       ],
       [0.4472136, 0.4472136, 0.4472136, 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.4472136, 0.4472136]])

In [42]:
print(tfidf.idf_)
#rint(tfidf.get_feature_names_out())

[1.40546511 1.40546511 1.40546511 1.40546511 1.40546511 1.40546511
 1.40546511 1.40546511 1.40546511 1.40546511]


### Custom features

Preparing our Own feature is called custom featues.

We create the data set and attributes to do feature extraction and selection.
1. Number of positive words in the review
2. Number of negative words in the review
3. Ratio of positive words and negative words.
etc...